#!/usr/bin/python
import socket, os

os.system("cls")
os.system("clear")
print "                     |     :   : ::::` ,:::` :   : ::::: :::::"
print "                   \ * /   :   : :   : :     :   :   :   :   :"
print "                   -*+*-   :   : ::::, :     :::::   :   :   :"
print "                   / * \   :   : :  :  :     :   :   :   :   :"
print "                     |     `:::, :   : `:::, :   : ::::: :   :"

host = socket.gethostname()
port = 1337
s = socket.socket()

s.bind((host, port))
print ""
print "                           Waiting for connection ..."
s.listen(1)
while True:
	c, addr = s.accept()
	print "                 Accepted connection from", addr
	print ""
	while True:
		cmd = raw_input(">>> ")
		c.send(cmd)
		print c.recv(1024)
		if cmd == "quit": break

s.close()
